export const DEFAULT_PARAMS = {
  wind_speed_mps: 5,
  wind_direction_from_deg: 270,
  current_speed_mps: 0.5,
  current_direction_to_deg: 90,
  timestep_minutes: 60,
  duration_hours: 24,
  wind_drift_coefficient: 0.03,
  current_coefficient: 1.0,
  particle_count: 100,
  diffusion_mps: 25,
  random_seed: 42,
  mode: "analyst_parameter_driven",
  vector_source: "analyst_input",
};
